---

- name: "Set repositories"
  template:
    src: default.repo.j2
    dest: /etc/yum.repos.d/default.repo
    owner: root
    group: root
    mode: 0644

- name: "Update packages"
  shell: "yum -y update"

- name: "Find pip package"
  stat:
    path: "{{ pip_path }}"
  register: installed

- name: "Install pip"
  block:
  - name: "Download package"
    get_url:
      url: "https://bootstrap.pypa.io/get-pip.py"
      dest: "{{ pip_path }}"
      mode: 0750
  - name: "Install"
    shell: "{{ pip_path }}"
  when: not installed.stat.exists

- name: "Install python packages"
  pip:
    name: PyMySQL

- name: "Install git and mariadb"
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - git
    - mariadb-server

- name: "Start mariadb service"
  service:
    name: mariadb
    state: started
    enabled: yes

- name: "Find pip package"
  stat:
    path: /root/.my.cnf
  register: mycnf

- name: "Idempotence to users"
  block:
  # Not allow: mysql --user="anonymous"
  - name: "Remove anonymous user account for localhost"
    mysql_user:
      name: ''
      host: localhost
      state: absent
  
  - name: "Change the root user’s password"
    mysql_user:
      name: root
      password: 1234
      check_implicit_admin: true
      host: localhost
  
  - name: 'Create .my.cnf with credentials'
    template:
      src: my.cnf
      dest: /root/.my.cnf
      mode: 400
  when: not mycnf.stat.exists
